In [3]:
!pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.8/150.8 MB 3.2 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 5.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 5.1 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 5.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 5.5 MB/s eta 0:00:00a 0:00:01


In [6]:
import torch

In [7]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
column_sum = torch.sum(x, dim=0)  # 计算每一列的总和
row_sum = torch.sum(x, dim=1)    # 计算每一行的总和A
print(column_sum)  # 输出: tensor([5, 7, 9])
print(row_sum)     # 输出: tensor([ 6, 15])

tensor([5, 7, 9])
tensor([ 6, 15])


In [8]:
row_sum.shape

torch.Size([2])

In [12]:
x/torch.sum(x,dim=1,keepdim=True)

tensor([[0.1667, 0.3333, 0.5000],
        [0.2667, 0.3333, 0.4000]])

In [13]:
torch.sum(x,dim=0,keepdim=True)

tensor([[5, 7, 9]])

x/torch.sum(x,dim=0)

torch.sum(x,dim=0)

In [24]:
x/torch.tensor([5, 7, 9])

tensor([[0.2000, 0.2857, 0.3333],
        [0.8000, 0.7143, 0.6667]])

In [25]:
torch.sum(x[0])

tensor(6)

In [1]:
a = [1, 2, 3]
print(a[:1])

[1]
