In [1]:
import pandas as pd
train = pd.read_csv(
    "./train.csv", index_col=0)
train.head(3)

tid1  tid2                          title1_zh                  title2_zh  \
id                                                                             
0      0     1      2017养老保险又新增两项，农村老人人人可申领，你领到了吗   警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京   
3      2     3  "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小   
1      2     4  "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港       GDP首超香港？深圳澄清：还差一点点……   

                                            title1_en  \
id                                                      
0   There are two new old-age insurance benefits f...   
3   "If you do not come to Shenzhen, sooner or lat...   
1   "If you do not come to Shenzhen, sooner or lat...   

                                            title2_en      label  
id                                                                
0   Police disprove "bird's nest congress each per...  unrelated  
3   Shenzhen's GDP outstrips Hong Kong? Shenzhen S...  unrelated  
1   The GDP overtopped Hong Kong? Shenzhen clarifi...  unrelated

In [2]:
cols = ['title1_zh',
        'title2_zh',
        'label']
train = train.loc[:, cols]
train.head(3)

title1_zh                  title2_zh      label
id                                                                         
0       2017养老保险又新增两项，农村老人人人可申领，你领到了吗   警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京  unrelated
3   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小  unrelated
1   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港       GDP首超香港？深圳澄清：还差一点点……  unrelated

In [3]:
text = 'I am Meng Lee, a data scientist based in Tokyo.'
words = text.split(' ')
words

['I', 'am', 'Meng', 'Lee,', 'a', 'data', 'scientist', 'based', 'in', 'Tokyo.']

In [4]:
!pip install jieba

Looking in indexes: http://pypi.tuna.tsinghua.edu.cn/simple
     ---------------------------------------- 0.0/19.2 MB ? eta -:--:--
     ---------------------------------------- 0.0/19.2 MB 1.4 MB/s eta 0:00:15
     --------------------------------------- 0.0/19.2 MB 991.0 kB/s eta 0:00:20
     --------------------------------------- 0.1/19.2 MB 787.7 kB/s eta 0:00:25
     ---------------------------------------- 0.2/19.2 MB 1.3 MB/s eta 0:00:15
      --------------------------------------- 0.4/19.2 MB 2.0 MB/s eta 0:00:10
      --------------------------------------- 0.4/19.2 MB 2.0 MB/s eta 0:00:10
     - -------------------------------------- 0.5/19.2 MB 1.6 MB/s eta 0:00:12
     - -------------------------------------- 0.6/19.2 MB 1.7 MB/s eta 0:00:11
     - -------------------------------------- 0.8/19.2 MB 2.1 MB/s eta 0:00:09
     -- ------------------------------------- 1.0/19.2 MB 2.2 MB/s eta 0:00:09
     -- ------------------------------------- 1.0/19.2 MB 2.3 MB/s eta 0:00:

In [5]:
import jieba.posseg as pseg

text = '我是李孟，在東京工作的數據科學家'
words = pseg.cut(text)
[word for word in words]

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\zhouyi\AppData\Local\Temp\jieba.cache
Loading model cost 0.763 seconds.
Prefix dict has been built successfully.


[pair('我', 'r'),
 pair('是', 'v'),
 pair('李孟', 'nr'),
 pair('，', 'x'),
 pair('在', 'p'),
 pair('東京', 'ns'),
 pair('工作', 'vn'),
 pair('的', 'uj'),
 pair('數據', 'n'),
 pair('科學家', 'n')]

In [6]:
def jieba_tokenizer(text):
    text = str(text)
    words = pseg.cut(text)
    return ' '.join([
        word for word, flag in words if flag != 'x'])

In [7]:
train['title2_tokenized'] = \
    train.loc[:, 'title2_zh'] \
         .apply(jieba_tokenizer)

In [8]:
train['title1_tokenized'] = \
    train.loc[:, 'title1_zh'] \
         .apply(jieba_tokenizer)

In [9]:
train.iloc[:, [0, 3]].head()

title1_zh                      title2_tokenized
id                                                                         
0       2017养老保险又新增两项，农村老人人人可申领，你领到了吗     警方 辟谣 鸟巢 大会 每人 领 5 万 仍 有 老人 坚持 进京
3   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港    深圳 GDP 首 超 香港 深圳 统计局 辟谣 只是 差距 在 缩小
1   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港              GDP 首 超 香港 深圳 澄清 还 差 一点点
2   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  去年 深圳 GDP 首 超 香港 深圳 统计局 辟谣 还 差 611 亿
9                "用大蒜鉴别地沟油的方法,怎么鉴别地沟油     吃 了 30 年 食用油 才 知道 一片 大蒜 轻松 鉴别 地沟油

In [10]:
train.iloc[:, [1, 4]].head()

title2_zh  \
id                               
0     警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京   
3    深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小   
1         GDP首超香港？深圳澄清：还差一点点……   
2   去年深圳GDP首超香港？深圳统计局辟谣：还差611亿   
9      吃了30年食用油才知道，一片大蒜轻松鉴别地沟油   

                                   title1_tokenized  
id                                                   
0          2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗  
3   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港  
1   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港  
2   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港  
9                        用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油

In [11]:
text = '狐狸被陌生人拍照'
words = pseg.cut(text)
words = [w for w, f in words]
words

['狐狸', '被', '陌生人', '拍照']

In [12]:
word_index = {
    word: idx
    for idx, word in enumerate(words)
}
word_index

{'狐狸': 0, '被': 1, '陌生人': 2, '拍照': 3}

In [13]:
print(words)
print([word_index[w] for w in words])

['狐狸', '被', '陌生人', '拍照']
[0, 1, 2, 3]


In [14]:
text = '陌生人被狐狸拍照'
words = pseg.cut(text)
words = [w for w, f in words]
print(words)
print([word_index[w] for w in words])

['陌生人', '被', '狐狸', '拍照']
[2, 1, 0, 3]


In [15]:
!pip install scikit-learn

Looking in indexes: http://pypi.tuna.tsinghua.edu.cn/simple
     ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
     ---------------------------------------- 0.1/10.6 MB ? eta -:--:--
      --------------------------------------- 0.2/10.6 MB 4.6 MB/s eta 0:00:03
      --------------------------------------- 0.2/10.6 MB 4.6 MB/s eta 0:00:03
     -- ------------------------------------- 0.8/10.6 MB 4.4 MB/s eta 0:00:03
     -- ------------------------------------- 0.8/10.6 MB 4.4 MB/s eta 0:00:03
     ---- ----------------------------------- 1.2/10.6 MB 4.4 MB/s eta 0:00:03
     ----- ---------------------------------- 1.4/10.6 MB 4.4 MB/s eta 0:00:03
     ----- ---------------------------------- 1.6/10.6 MB 4.3 MB/s eta 0:00:03
     ------- -------------------------------- 1.9/10.6 MB 4.7 MB/s eta 0:00:02
     --------- ------------------------------ 2.4/10.6 MB 5.5 MB/s eta 0:00:02
     --------- ------------------------------ 2.6/10.6 MB 5.3 MB/s eta 0:00:02
     -

In [16]:
! pip install tensorflow

Looking in indexes: http://pypi.tuna.tsinghua.edu.cn/simple
     ---------------------------------------- 0.0/376.9 MB ? eta -:--:--
     ---------------------------------------- 0.1/376.9 MB 6.8 MB/s eta 0:00:56
     ---------------------------------------- 0.4/376.9 MB 4.6 MB/s eta 0:01:22
     ---------------------------------------- 0.4/376.9 MB 4.2 MB/s eta 0:01:30
     ---------------------------------------- 0.4/376.9 MB 4.2 MB/s eta 0:01:30
     ---------------------------------------- 0.9/376.9 MB 4.0 MB/s eta 0:01:34
     ---------------------------------------- 0.9/376.9 MB 4.0 MB/s eta 0:01:34
     ---------------------------------------- 0.9/376.9 MB 4.0 MB/s eta 0:01:34
     ---------------------------------------- 1.4/376.9 MB 3.7 MB/s eta 0:01:41
     ---------------------------------------- 1.5/376.9 MB 3.5 MB/s eta 0:01:48
     ---------------------------------------- 2.0/376.9 MB 4.3 MB/s eta 0:01:27
     ---------------------------------------- 2.3/376.9 MB 4.4 MB/s

  You can safely remove it manually.



     ---------------- ------------------- 176.7/376.9 MB 494.9 kB/s eta 0:06:45
     ---------------- ------------------- 176.7/376.9 MB 494.9 kB/s eta 0:06:45
     ---------------- ------------------- 176.7/376.9 MB 493.0 kB/s eta 0:06:47
     ---------------- ------------------- 176.7/376.9 MB 494.5 kB/s eta 0:06:45
     ---------------- ------------------- 176.7/376.9 MB 494.5 kB/s eta 0:06:45
     ---------------- ------------------- 176.8/376.9 MB 491.9 kB/s eta 0:06:47
     ---------------- ------------------- 176.8/376.9 MB 491.2 kB/s eta 0:06:48
     ---------------- ------------------- 176.8/376.9 MB 491.2 kB/s eta 0:06:48
     ---------------- ------------------- 176.8/376.9 MB 488.6 kB/s eta 0:06:50
     ---------------- ------------------- 176.8/376.9 MB 487.1 kB/s eta 0:06:51
     ---------------- ------------------- 176.8/376.9 MB 486.0 kB/s eta 0:06:52
     ---------------- ------------------- 176.8/376.9 MB 486.0 kB/s eta 0:06:52
     ---------------- -----------------

In [25]:
from tensorflow.keras.preprocessing.text import Tokenizer
MAX_NUM_WORDS = 10000
tokenizer = Tokenizer(num_words=MAX_NUM_WORDS)

In [26]:
corpus_x1 = train.title1_tokenized
corpus_x1

id
0                2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗
3         你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
1         你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
2         你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
9                              用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油
                               ...                       
321185       萨拉 赫 人气 爆棚 埃及 总统大选 未 参选 获 百万 选票 现任 总统 压力 山 大
321182       萨拉 赫 人气 爆棚 埃及 总统大选 未 参选 获 百万 选票 现任 总统 压力 山 大
321184       萨拉 赫 人气 爆棚 埃及 总统大选 未 参选 获 百万 选票 现任 总统 压力 山 大
321186       萨拉 赫 人气 爆棚 埃及 总统大选 未 参选 获 百万 选票 现任 总统 压力 山 大
321188          萨达姆 此项 计划 没有 此国 破坏 的话 美国 还 会 对 伊拉克 发动战争 吗
Name: title1_tokenized, Length: 320552, dtype: object

In [27]:
corpus_x1 = train.title1_tokenized
corpus_x2 = train.title2_tokenized
corpus = pd.concat([
    corpus_x1, corpus_x2])
corpus

id
0                2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗
3         你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
1         你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
2         你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
9                              用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油
                               ...                       
321185                   西媒 曝 萨拉 赫 被 推荐 至 巴萨 经纪人 辟谣 并未 发生
321182                            萨拉 赫 经纪人 辟谣 与 巴萨 传闻 不 实
321184                 萨拉 赫 辟谣 传闻 埃及 非常 团结 我们 之间 没有 任何 分歧
321186                   辟谣 不 实 传闻 埃及 足协 主席 萨拉 赫 不会 提前 离队
321188                         萨达姆 女儿 辟谣 萨达姆 政权 二号 人物 没 死
Length: 641104, dtype: object

In [28]:
pd.DataFrame(corpus.iloc[:5],
             columns=['title'])

title
id                                                 
0          2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗
3   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
1   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
2   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
9                        用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油

In [29]:
tokenizer.fit_on_texts(corpus)

In [30]:
x1_train = tokenizer \
    .texts_to_sequences(corpus_x1)
x2_train = tokenizer \
    .texts_to_sequences(corpus_x2)

In [31]:
for seq in x1_train[:1]:
    print([tokenizer.index_word[idx] for idx in seq])

['2017', '养老保险', '又', '新增', '两项', '农村', '老人', '人人', '可', '申领', '你', '领到', '了', '吗']


In [32]:
for seq in x1_train[:10]:
    print(len(seq), seq[:5], ' ...')

14 [217, 1268, 32, 1178, 5967]  ...
19 [4, 10, 47, 678, 2558]  ...
19 [4, 10, 47, 678, 2558]  ...
19 [4, 10, 47, 678, 2558]  ...
9 [31, 320, 3372, 3062, 1]  ...
19 [4, 10, 47, 678, 2558]  ...
6 [7, 2221, 1, 2072, 7]  ...
19 [4, 10, 47, 678, 2558]  ...
14 [1281, 1211, 427, 3, 3245]  ...
9 [31, 320, 3372, 3062, 1]  ...


In [33]:
max_seq_len = max([
    len(seq) for seq in x1_train])
max_seq_len

61

In [34]:
import keras
MAX_SEQUENCE_LENGTH = 20
x1_train = keras \
    .preprocessing \
    .sequence \
    .pad_sequences(x1_train,
                   maxlen=MAX_SEQUENCE_LENGTH)

In [35]:
x2_train = keras \
    .preprocessing \
    .sequence \
    .pad_sequences(x2_train,
                   maxlen=MAX_SEQUENCE_LENGTH)

In [36]:
x1_train[:5]

array([[   0,    0,    0,    0,    0,    0,  217, 1268,   32, 1178, 5967,
          25,  489, 2877,  116, 5559,    4, 1850,    2,   13],
       [   0,    4,   10,   47,  678, 2558,    4,  166,   34,   17,   47,
        5150,   63,   15,  678, 4502, 3211,   23,  284, 1181],
       [   0,    4,   10,   47,  678, 2558,    4,  166,   34,   17,   47,
        5150,   63,   15,  678, 4502, 3211,   23,  284, 1181],
       [   0,    4,   10,   47,  678, 2558,    4,  166,   34,   17,   47,
        5150,   63,   15,  678, 4502, 3211,   23,  284, 1181],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          31,  320, 3372, 3062,    1,   95,   98, 3372, 3062]])

In [37]:
import numpy as np

# 定義每一個分類對應到的索引數字
label_to_index = {
    'unrelated': 0,
    'agreed': 1,
    'disagreed': 2
}

# 將分類標籤對應到剛定義的數字
y_train = train.label.apply(
    lambda x: label_to_index[x])

y_train = np.asarray(y_train) \
            .astype('float32')

y_train[:5]

array([0., 0., 0., 0., 1.], dtype=float32)

In [38]:
y_train = keras \
    .utils \
    .to_categorical(y_train)

y_train[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [41]:
from sklearn.model_selection \
    import train_test_split

VALIDATION_RATIO = 0.1
# 小彩蛋
RANDOM_STATE = 9527

x1_train, x1_val, \
x2_train, x2_val, \
y_train, y_val = \
    train_test_split(
        x1_train, x2_train, y_train,
        test_size=VALIDATION_RATIO,
        random_state=RANDOM_STATE
)

In [42]:
print("Training Set")
print("-" * 10)
print(f"x1_train: {x1_train.shape}")
print(f"x2_train: {x2_train.shape}")
print(f"y_train : {y_train.shape}")

print("-" * 10)
print(f"x1_val:   {x1_val.shape}")
print(f"x2_val:   {x2_val.shape}")
print(f"y_val :   {y_val.shape}")
print("-" * 10)
print("Test Set")

Training Set
----------
x1_train: (288496, 20)
x2_train: (288496, 20)
y_train : (288496, 3)
----------
x1_val:   (32056, 20)
x2_val:   (32056, 20)
y_val :   (32056, 3)
----------
Test Set


In [43]:
for i, seq in enumerate(x1_train[:5]):
    print(f"新聞標題 {i + 1}: ")
    print([tokenizer.index_word.get(idx, '') for idx in seq])
    print()

新聞標題 1: 
['', '', '', '', '', '营养师', '补充', '这', '4', '种', '营养', '能', '帮', '你', '降血压', '你', '一样', '都', '不吃', '么']

新聞標題 2: 
['', '', '', '', '', '', '', '', '', '刘涛', '现场', '痛哭', '发飙', '要', '离婚', '直接', '把', '旁边', '的', '了']

新聞標題 3: 
['', '', '', '', '', '', '', '', '', '', '', 'nba', '被', '球星', '诞生', '火箭', '骑士', '同', '抢', '交易']

新聞標題 4: 
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '海口', '飞机', '撒药治', '白蛾']

新聞標題 5: 
['', '', '', '', '', '', '', '', '网', '曝', '杜', '海涛', '与', '沈梦辰', '已', '分手', '疑似', '女方', '劈', '腿']



In [ ]:
from keras import layers
embedding_layer = layers.Embedding(
    MAX_NUM_WORDS, NUM_EMBEDDING_DIM)