In [1]:
import torch

# 创建两个三维张量，分别代表一批矩阵
batch1 = torch.randn(3, 2, 4) ` # 3个样本，每个样本有2x4的矩阵
batch2 = torch.randn(3, 4, 3)  # 3个样本，每个样本有4x3的矩阵

In [2]:
batch1,batch2

(tensor([[[-0.5058, -1.7764,  0.8482, -0.4564],
          [ 0.4855, -1.3741,  0.3162,  1.4208]],
 
         [[ 0.5108,  1.2719, -0.2239, -0.9519],
          [ 1.3478,  0.1403, -0.7451, -0.1817]],
 
         [[ 1.4621,  0.5548, -1.7351, -1.1533],
          [ 0.5527, -0.5303,  0.7634, -1.0676]]]),
 tensor([[[ 1.0228, -0.4964, -0.6718],
          [ 1.0363,  0.6213,  0.7759],
          [ 1.1077, -0.6238,  0.4617],
          [-1.7098, -0.5387,  0.4108]],
 
         [[ 1.6637,  0.9265, -0.1406],
          [-0.3899,  0.8584,  0.5518],
          [ 0.3573, -0.0803,  0.8025],
          [-0.8953,  0.5448, -0.9197]],
 
         [[-0.3083, -1.6702, -1.2177],
          [ 2.4653,  0.4686, -1.8077],
          [ 0.0948, -0.9383,  0.1560],
          [-0.2811,  1.1620, -0.0716]]]))

In [4]:
a = batch1@batch2
a , a.shape

(tensor([[[-0.6383, -1.1358, -0.8343],
          [-3.0063, -2.0574, -0.6626]],
 
         [[ 1.1260,  1.0644,  1.3259],
          [ 2.0840,  1.3300, -0.5428]],
 
         [[ 1.0767, -1.8941, -2.9712],
          [-1.1054, -3.1286,  0.4812]]]),
 torch.Size([3, 2, 3]))