In [1]:
import numpy as np

In [2]:
x = np.array([0, 1])
x

array([0, 1])

In [3]:
w = np.array([0.5, 0.5])
w

array([0.5, 0.5])

In [4]:
b = -0.7

In [5]:
w*x

array([0. , 0.5])

In [6]:
np.dot(w,x)

0.5

In [7]:
np.dot(w,x) + b

-0.19999999999999996